modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/samolego/ChestRefill/issues"
source = "https://github.com/samolego/ChestRefill"
license = "MIT"

[[mods]]
modId = "chestrefill"
version = "${version}"
displayName = "Chest Refill"
authors = "samo_lego"
description = '''
A serverside mod that refills loot containers.
'''
logoFile = "chestrefill_icon.png"

[[dependencies.chestrefill]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestrefill]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"