modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/samolego/ChestRefill/issues"
source = "https://github.com/samolego/ChestRefill"
license = "MIT"

[[mods]]
modId = "chestrefill"
version = "${version}"
displayName = "Chest Refill"
authors = "samo_lego"
description = '''
A serverside mod that refills loot containers.
'''
logoFile = "chestrefill_icon.png"

[[dependencies.chestrefill]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chestrefill]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"


# C2B Lib
modLoader = "javafml"
loaderVersion = "[37,)"
license = "LGPL-v3.0"

[[mods]]
modId = "config2brigadier"
version = "${c2b_version}"
displayName = "Config to Brigadier"
authors = "samo_lego"
description = '''
A library to automagically generate in-game command for config editing.
'''

[[dependencies.config2brigadier]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.config2brigadier]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
